fix: Allow blocking API tokens
supabase/realtime pull request #1069
Opened 2024-06-04 17:02 UTC by filipecabaco

## What kind of change does this PR introduce?

Allow blocking API tokens

2024-06-04 17:03 UTC, abc3 approved these changes

2024-06-04 17:23 UTC, w3b6x9 requested changes

2024-06-04 17:23 UTC, w3b6x9 commented on lib/realtime_web/router.ex
> +    blocklist = Application.get_env(:realtime, :block_list, [])
@filipecabaco you named it `blocklist` in runtime.exs: https://github.com/supabase/realtime/pull/1069/files#diff-e43c5cbf91db7a8062b6cb860cbf118296c1b4c7ee32fdcf702e54234ba38092R56

```suggestion
    blocklist = Application.get_env(:realtime, :blocklist, [])
```

2024-06-04 17:25 UTC, w3b6x9 approved these changes

2024-06-04 18:52 UTC, chasers approved these changes

2024-06-05 00:07 UTC, merged

2024-06-05 00:07 UTC, kiwicopple commented
:tada: This PR is included in version 2.29.4 :tada:

The release is available on [GitHub release](https://github.com/supabase/realtime/releases/tag/v2.29.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: