fix: avoid pool size override
supabase/realtime pull request #1115
Opened 2024-08-03 22:19 UTC by filipecabaco

## What kind of change does this PR introduce?

Avoid pool size override

2024-08-03 22:38 UTC, chasers approved these changes

2024-08-03 22:38 UTC, chasers commented
Approved for now, but can we have a test where the actual pool size(s) are what we are setting?

2024-08-03 22:40 UTC, w3b6x9 requested changes
before this goes in let's make sure `check_tenant_connection(tenant, "replication_slot_teardown")` uses just one db conn.

2024-08-03 23:56 UTC, w3b6x9 commented on lib/realtime/database.ex
> +  @spec check_tenant_connection(Tenant.t(), binary(), integer() | nil) ::
```suggestion
  @spec check_tenant_connection(Tenant.t(), binary(), boolean()) ::
```

2024-08-03 23:59 UTC, w3b6x9 approved these changes

2024-08-04 00:06 UTC, merged

2024-08-04 00:07 UTC, kiwicopple commented
:tada: This PR is included in version 2.30.19 :tada:

The release is available on [GitHub release](https://github.com/supabase/realtime/releases/tag/v2.30.19)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: