feat: high res commit_timestamp in Postgres change payload
supabase/realtime pull request #453
Opened 2023-01-19 14:04 UTC by chasers

- `commit_timestamp` from walrus is now high res `2023-01-19 13:58:43.671581+00` 
  - I tested that with `Date.parse` and it works just the same
  - Previously was `2023-01-19T13:58:43Z`
- Latency for Postgres changes is now accurate in the Inspector
- Latency on Footer matches precision and style as Postgres change latency

<img width="1057" alt="Screen Shot 2023-01-19 at 6 58 57 AM" src="https://user-images.githubusercontent.com/1019814/213462334-4e8abb6f-e321-4223-b878-201d6e762856.png">

2023-01-19 15:01 UTC, olirice requested changes
@chasers I'm on board with increasing precision but if we are going to edit the walrus code lets make that change at supabase/walrus first and then port the migration here afterward. If they get out-of-sync the next update to `realtime.apply_rls` in walrus will revert this change

Extra context:
Previous issues related to timestamp formatting 
https://github.com/supabase/walrus/issues/37
https://github.com/supabase/walrus/issues/14

2023-01-19 18:55 UTC, w3b6x9 requested changes
This needs to be in ISO 8601 format.

2023-01-19 22:00 UTC, chasers commented
<img width="923" alt="Screen Shot 2023-01-19 at 3 00 27 PM" src="https://user-images.githubusercontent.com/1019814/213571632-fe443ed7-7ea7-4518-ac19-af6e0c78e3dd.png">

2023-01-19 22:04 UTC, chasers commented
@olirice sure thing, but this repo and the migration here is what actually defines the `apply_rls` function. Does some other system try to define it?

2023-01-19 23:50 UTC, w3b6x9 commented
>Does some other system try to define it?

@chasers these types of things originate in the `walrus` repo and after it's approved and merged there then we take the migration(s) and apply them to Realtime. All changes should originate from `walrus` and then copied over to `realtime` repo.

2023-01-20 22:55 UTC, olirice commented
once there's consensus on exactly what format/precision to use I'll make the walrus PR and get it under test. lmk!

2023-01-28 15:32 UTC, chasers commented
@w3b6x9 I'd like to use these hi-res timestamps to show a client how to monitor Realtime on Monday. 

Is there an issue you see with ISO 8601 with millis?

2023-01-28 18:05 UTC, w3b6x9 commented
> Is there an issue you see with ISO 8601 with millis?

@chasers nope, we just need the migration over in walrus first.

2023-01-29 21:12 UTC, w3b6x9 commented
@olirice can you please take a quick look at https://github.com/supabase/realtime/blob/0d177e1078c2efdb612b0316b5f9629f5543cac8/priv/repo/postgres/migrations/20230119133233_millisecond_precision_for_walrus.exs?

2023-01-30 19:53 UTC, w3b6x9 approved these changes

2023-01-30 20:02 UTC, merged

2023-02-22 23:40 UTC, kiwicopple commented
:tada: This PR is included in version 2.6.0 :tada:

The release is available on [GitHub release](https://github.com/supabase/realtime/releases/tag/v2.6.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-03-14 18:00 UTC, kiwicopple commented
:tada: This PR is included in version 2.6.0 :tada:

The release is available on [GitHub release](https://github.com/supabase/realtime/releases/tag/v2.6.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: