feat: use the Inspector with a JWT signed with custom claims
supabase/realtime pull request #592
Opened 2023-05-11 23:32 UTC by chasers

2023-05-12 07:07 UTC, abc3 approved these changes

2023-06-06 23:49 UTC, w3b6x9 commented on lib/realtime_web/live/inspector_live/conn_component.html.heex
> +            <p class="text-gray-600 text-xs italic">An Auth user JWT optionally signed with custom claims</p>
@chasers if the only purpose is to pass in a JWT with custom claims then I would just be explicit and mention that

```suggestion
            <p class="text-gray-600 text-xs italic">A manually signed JWT with your custom claims</p>
```

or something to that effect.

2023-06-06 23:51 UTC, w3b6x9 commented on assets/package.json
> +    "@supabase/supabase-js": "^2.21.0"
@chasers since you're already version bumping might as well version bump to the latest:

```suggestion
    "@supabase/supabase-js": "^2.24.0"
```

2023-06-07 04:23 UTC, w3b6x9 requested changes
@chasers just making a note that the `Bearer` custom claims JWT token isn't working. It never shows up in the `realtime.subscription` table. Only the `Token` (Supabase API key like `anon`, `service_role`) shows up.

2023-06-27 12:10 UTC, chasers commented
✅ [docs updated](https://github.com/supabase/supabase/pull/15388)

2023-06-27 12:11 UTC, merged

2023-06-27 12:12 UTC, kiwicopple commented
:tada: This PR is included in version 2.17.0 :tada:

The release is available on [GitHub release](https://github.com/supabase/realtime/releases/tag/v2.17.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: