fix: Migration error for Cloud SQL
supabase/realtime pull request #617
Opened 2023-07-05 23:34 UTC by nkreiger

## What kind of change does this PR introduce?

Bug fix/Chore. 

## What is the current behavior?

The function realtime.list_changes is created, and sets the log_min_messages to 'fatal' for each session it runs.

## What is the new behavior?

The function realtime.list_changes is created, and if the your permissions are not a super use, it does not set the log_min_messages to 'fatal', but relies on the admin of the DB to set this at the appropriate level

## Additional context

This allows the migration to proceed for Cloud SQL setups that do not allow you to have a super user.

2023-07-06 17:03 UTC, olirice requested changes
would be best to make this a separate migration that `create or replaces` the function rather than editing an existing migration

2023-07-06 17:03 UTC, olirice commented on lib/extensions/postgres_cdc_rls/repo/migrations/20230328144023_create_list_changes_function.ex
> +          set log_min_messages to ''fatal''
if this is the only line of difference, can the if statement be moved into a separate posters query and add/remove this line using string interpolation?

2023-07-06 17:32 UTC, w3b6x9 commented
@nkreiger thanks for your contribution!

can you also create a fresh migration file and move this in there?

2023-07-06 17:32 UTC, w3b6x9 requested changes
see: https://github.com/supabase/realtime/pull/617#issuecomment-1624061380

2023-07-08 18:16 UTC, nkreiger commented
@w3b6x9 yep, I was going to actually comment that since its the only change maybe it could be broken out. I'll do this now

2023-07-08 18:27 UTC, nkreiger commented
@olirice @w3b6x9 I broke out the steps.

If I were to remove the `IF` statement entirely from the original migration, then the DB migration would still fail on that step with a permissions error, and I would get stuck there having to manually bump the migration passed it.

Maybe cleaner than the if statement if I just catch and ignore an exception? Let me know if thats preferable or you have alternative ideas.

2023-07-10 19:24 UTC, olirice commented
> If I were to remove the `IF` statement entirely from the original migration, then the DB migration would still fail on that step with a permissions error, and I would get stuck there having to manually bump the migration passed it.
> 
> Maybe cleaner than the if statement if I just catch and ignore an exception? Let me know if thats preferable or you have alternative ideas.

could you please provide the full error message you're seeing?

2023-07-19 19:12 UTC, nkreiger commented
@olirice sorry I had to pull it out because of the error and haven't had a chance to setup an example environment, will hopefully get back to you asap later this week or early next!

2023-11-01 03:38 UTC, nkreiger commented
@olirice apologies for the delay, this is the error:

```
03:36:35.796 project=realtime external_id=realtime [error] Error starting Postgres Extention: {:error,
 {:shutdown,
  {:failed_to_start_child, Extensions.PostgresCdcRls.Migrations,
   {%Postgrex.Error{
      message: nil,
      postgres: %{
        code: :insufficient_privilege,
        file: "guc.c",
        line: "8120",
        message: "permission denied to set parameter \"log_min_messages\"",
        pg_code: "42501",
        routine: "set_config_option_ext",
        severity: "ERROR",
        unknown: "ERROR"
      },
      connection_id: 254962,
      query: nil
    },
    [
      {Ecto.Adapters.SQL, :raise_sql_call_error, 1,
       [
         file: 'lib/ecto/adapters/sql.ex',
         line: 932,
         error_info: %{module: Exception}
       ]},
      {Enum, :"-map/2-lists^map/1-0-", 2, [file: 'lib/enum.ex', line: 1658]},
      {Ecto.Adapters.SQL, :execute_ddl, 4,
       [file: 'lib/ecto/adapters/sql.ex', line: 1024]},
      {Ecto.Migration.Runner, :log_and_execute_ddl, 3,
       [file: 'lib/ecto/migration/runner.ex', line: 352]},
      {Ecto.Migration.Runner, :"-flush/0-fun-1-", 6,
       [file: 'lib/ecto/migration/runner.ex', line: 117]},
      {Enum, :"-reduce/3-lists^foldl/2-0-", 3,
       [file: 'lib/enum.ex', line: 2468]},
      {Ecto.Migration.Runner, :flush, 0,
       [file: 'lib/ecto/migration/runner.ex', line: 116]},
      {Ecto.Migration.Runner, :perform_operation, 3,
       [file: 'lib/ecto/migration/runner.ex', line: 289]}
    ]}}}}
```

2023-11-02 16:46 UTC, w3b6x9 commented
@nkreiger It's been awhile so just wanted to confirm we're on the same page:

1. need to update an existing migration file so it runs successfully
2. create another migration file replacing the function so that it doesn't set `log_min_messages` on every invocation

We're not going to do step 1 b/c it would change an existing migration file that's already been run on hosted and self-hosted Realtime projects.

We recommend that you fork this Realtime repo and add these necessary migrations to your version of Realtime so you're not blocked when using it against a Cloud SQL database.

2023-11-02 16:46 UTC, closed without merging