fix: Restrict seed file to handle test and dev environments
supabase/realtime pull request #736
Opened 2023-11-14 16:55 UTC by filipecabaco

## What kind of change does this PR introduce?

Restrict seed file to handle test and dev environments

2023-11-14 17:11 UTC, chetan requested changes

2023-11-14 17:11 UTC, chetan commented on priv/repo/seeds.exs
> +IO.inspect(Mix.env())
debug?

2023-11-14 21:50 UTC, filipecabaco commented on priv/repo/seeds.exs
>  tenant_name = "realtime-dev-tenant"
you are right, I'll doublecheck why this value was set

2023-11-14 21:50 UTC, filipecabaco commented on priv/repo/seeds.exs
> +IO.inspect(Mix.env())
🤦 yeah removing

2023-11-14 21:53 UTC, filipecabaco commented on priv/repo/seeds.exs
>  tenant_name = "realtime-dev-tenant"
checked on other repos and indeed does not make sense to have this value from what I gather, changed it to the value `realtime-dev`

2023-11-15 13:46 UTC, chetan approved these changes
LGTM

2023-11-15 22:14 UTC, w3b6x9 approved these changes
lgtm!

2023-11-15 23:31 UTC, merged

2023-11-15 23:32 UTC, kiwicopple commented
:tada: This PR is included in version 2.25.32 :tada:

The release is available on [GitHub release](https://github.com/supabase/realtime/releases/tag/v2.25.32)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: